name: Deploy WP Theme (FTP)

on:
  push:
    branches: ["main"]
    paths:
      - "sbd-brutalist/**"
      - ".github/workflows/deploy-theme-ftp.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy theme via FTP (verbose)
        uses: sebastianpopp/ftp-action@v2.0.0
        with:
          host: ${{ secrets.FTP_HOST }}
          user: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          port: ${{ secrets.FTP_PORT }}
          localDir: "sbd-brutalist"
          remoteDir: "${{ secrets.FTP_DEST }}"